/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

--drop schema if exists "proc" cascade;

--CREATE SCHEMA if not exists "proc";
{{ template "register_table_events.sql".}} 
