/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

--drop schema if exists "proc" cascade;

--CREATE SCHEMA if not exists "proc";
{{ template "connection_create_proc.sql".}} 
{{ template "connection_update_proc.sql".}} {{ template "connection_patch_proc.sql".}} 
{{ template "connection_delete_proc.sql".}} 
{{ template "connection_undo_delete_proc.sql".}} 
{{ template "transformer_create_proc.sql".}} 
{{ template "transformer_update_proc.sql".}} {{ template "transformer_patch_proc.sql".}} 
{{ template "transformer_delete_proc.sql".}} 
{{ template "transformer_undo_delete_proc.sql".}} 
{{ template "dataset_create_proc.sql".}} 
{{ template "dataset_update_proc.sql".}} {{ template "dataset_patch_proc.sql".}} 
{{ template "dataset_delete_proc.sql".}} 
{{ template "dataset_undo_delete_proc.sql".}} 
{{ template "column_create_proc.sql".}} 
{{ template "column_update_proc.sql".}} {{ template "column_patch_proc.sql".}} 
{{ template "column_delete_proc.sql".}} 
{{ template "column_undo_delete_proc.sql".}} 
{{ template "mapper_create_proc.sql".}} 
{{ template "mapper_update_proc.sql".}} {{ template "mapper_patch_proc.sql".}} 
{{ template "mapper_delete_proc.sql".}} 
{{ template "mapper_undo_delete_proc.sql".}} 
{{ template "transformation_create_proc.sql".}} 
{{ template "transformation_update_proc.sql".}} {{ template "transformation_patch_proc.sql".}} 
{{ template "transformation_delete_proc.sql".}} 
{{ template "transformation_undo_delete_proc.sql".}} 
{{ template "processlog_create_proc.sql".}} 
{{ template "processlog_update_proc.sql".}} {{ template "processlog_patch_proc.sql".}} 
{{ template "processlog_delete_proc.sql".}} 
{{ template "processlog_undo_delete_proc.sql".}} 
{{ template "importdata_create_proc.sql".}} 
{{ template "importdata_update_proc.sql".}} {{ template "importdata_patch_proc.sql".}} 
{{ template "importdata_delete_proc.sql".}} 
{{ template "importdata_undo_delete_proc.sql".}} 
{{ template "sql_create_proc.sql".}} 
{{ template "sql_update_proc.sql".}} {{ template "sql_patch_proc.sql".}} 
{{ template "sql_delete_proc.sql".}} 
{{ template "sql_undo_delete_proc.sql".}} 
{{ template "job_create_proc.sql".}} 
{{ template "job_update_proc.sql".}} {{ template "job_patch_proc.sql".}} 
{{ template "job_delete_proc.sql".}} 
{{ template "job_undo_delete_proc.sql".}} 
{{ template "schedule_create_proc.sql".}} 
{{ template "schedule_update_proc.sql".}} {{ template "schedule_patch_proc.sql".}} 
{{ template "schedule_delete_proc.sql".}} 
{{ template "schedule_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} {{ template "auditlog_patch_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 
{{ template "user_create_proc.sql".}} 
{{ template "user_update_proc.sql".}} {{ template "user_patch_proc.sql".}} 
{{ template "user_delete_proc.sql".}} 
{{ template "user_undo_delete_proc.sql".}} 
{{ template "role_create_proc.sql".}} 
{{ template "role_update_proc.sql".}} {{ template "role_patch_proc.sql".}} 
{{ template "role_delete_proc.sql".}} 
{{ template "role_undo_delete_proc.sql".}} 
{{ template "permission_create_proc.sql".}} 
{{ template "permission_update_proc.sql".}} {{ template "permission_patch_proc.sql".}} 
{{ template "permission_delete_proc.sql".}} 
{{ template "permission_undo_delete_proc.sql".}} 
{{ template "accessholder_create_proc.sql".}} 
{{ template "accessholder_update_proc.sql".}} {{ template "accessholder_patch_proc.sql".}} 
{{ template "accessholder_delete_proc.sql".}} 
{{ template "accessholder_undo_delete_proc.sql".}} 
{{ template "environmenttype_create_proc.sql".}} 
{{ template "environmenttype_update_proc.sql".}} {{ template "environmenttype_patch_proc.sql".}} 
{{ template "environmenttype_delete_proc.sql".}} 
{{ template "environmenttype_undo_delete_proc.sql".}} 
{{ template "database_create_proc.sql".}} 
{{ template "database_update_proc.sql".}} {{ template "database_patch_proc.sql".}} 
{{ template "database_delete_proc.sql".}} 
{{ template "database_undo_delete_proc.sql".}} 
{{ template "request_create_proc.sql".}} 
{{ template "request_update_proc.sql".}} {{ template "request_patch_proc.sql".}} 
{{ template "request_delete_proc.sql".}} 
{{ template "request_undo_delete_proc.sql".}} 
{{ template "new_workspace.sql".}} 
{{ template "workspace_create_proc.sql".}} 
{{ template "workspace_update_proc.sql".}} {{ template "workspace_patch_proc.sql".}} 
{{ template "workspace_delete_proc.sql".}} 
{{ template "workspace_undo_delete_proc.sql".}} 
{{ template "sqlquery_create_proc.sql".}} 
{{ template "sqlquery_update_proc.sql".}} {{ template "sqlquery_patch_proc.sql".}} 
{{ template "sqlquery_delete_proc.sql".}} 
{{ template "sqlquery_undo_delete_proc.sql".}} 
{{ template "history_create_proc.sql".}} 
{{ template "history_update_proc.sql".}} {{ template "history_patch_proc.sql".}} 
{{ template "history_delete_proc.sql".}} 
{{ template "history_undo_delete_proc.sql".}} 
{{ template "session_create_proc.sql".}} 
{{ template "session_update_proc.sql".}} {{ template "session_patch_proc.sql".}} 
{{ template "session_delete_proc.sql".}} 
{{ template "session_undo_delete_proc.sql".}} 
{{ template "sessionstage_create_proc.sql".}} 
{{ template "sessionstage_update_proc.sql".}} {{ template "sessionstage_patch_proc.sql".}} 
{{ template "sessionstage_delete_proc.sql".}} 
{{ template "sessionstage_undo_delete_proc.sql".}} 
{{ template "koksmat_create_proc.sql".}} 
{{ template "koksmat_update_proc.sql".}} {{ template "koksmat_patch_proc.sql".}} 
{{ template "koksmat_delete_proc.sql".}} 
{{ template "koksmat_undo_delete_proc.sql".}} 
{{ template "pizzaorder_create_proc.sql".}} 
{{ template "pizzaorder_update_proc.sql".}} {{ template "pizzaorder_patch_proc.sql".}} 
{{ template "pizzaorder_delete_proc.sql".}} 
{{ template "pizzaorder_undo_delete_proc.sql".}} 
{{ template "magicbutton_create_proc.sql".}} 
{{ template "magicbutton_update_proc.sql".}} {{ template "magicbutton_patch_proc.sql".}} 
{{ template "magicbutton_delete_proc.sql".}} 
{{ template "magicbutton_undo_delete_proc.sql".}} 
{{ template "feature_create_proc.sql".}} 
{{ template "feature_update_proc.sql".}} {{ template "feature_patch_proc.sql".}} 
{{ template "feature_delete_proc.sql".}} 
{{ template "feature_undo_delete_proc.sql".}} 
{{ template "app_create_proc.sql".}} 
{{ template "app_update_proc.sql".}} {{ template "app_patch_proc.sql".}} 
{{ template "app_delete_proc.sql".}} 
{{ template "app_undo_delete_proc.sql".}} 
{{ template "featureset_create_proc.sql".}} 
{{ template "featureset_update_proc.sql".}} {{ template "featureset_patch_proc.sql".}} 
{{ template "featureset_delete_proc.sql".}} 
{{ template "featureset_undo_delete_proc.sql".}} 

