/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "connection_create_proc.sql".}} 
{{ template "connection_update_proc.sql".}} 
{{ template "connection_delete_proc.sql".}} 
{{ template "connection_undo_delete_proc.sql".}} 
{{ template "transformer_create_proc.sql".}} 
{{ template "transformer_update_proc.sql".}} 
{{ template "transformer_delete_proc.sql".}} 
{{ template "transformer_undo_delete_proc.sql".}} 
{{ template "dataset_create_proc.sql".}} 
{{ template "dataset_update_proc.sql".}} 
{{ template "dataset_delete_proc.sql".}} 
{{ template "dataset_undo_delete_proc.sql".}} 
{{ template "column_create_proc.sql".}} 
{{ template "column_update_proc.sql".}} 
{{ template "column_delete_proc.sql".}} 
{{ template "column_undo_delete_proc.sql".}} 
{{ template "mapper_create_proc.sql".}} 
{{ template "mapper_update_proc.sql".}} 
{{ template "mapper_delete_proc.sql".}} 
{{ template "mapper_undo_delete_proc.sql".}} 
{{ template "transformation_create_proc.sql".}} 
{{ template "transformation_update_proc.sql".}} 
{{ template "transformation_delete_proc.sql".}} 
{{ template "transformation_undo_delete_proc.sql".}} 
{{ template "processlog_create_proc.sql".}} 
{{ template "processlog_update_proc.sql".}} 
{{ template "processlog_delete_proc.sql".}} 
{{ template "processlog_undo_delete_proc.sql".}} 
{{ template "importdata_create_proc.sql".}} 
{{ template "importdata_update_proc.sql".}} 
{{ template "importdata_delete_proc.sql".}} 
{{ template "importdata_undo_delete_proc.sql".}} 
{{ template "sql_create_proc.sql".}} 
{{ template "sql_update_proc.sql".}} 
{{ template "sql_delete_proc.sql".}} 
{{ template "sql_undo_delete_proc.sql".}} 
{{ template "job_create_proc.sql".}} 
{{ template "job_update_proc.sql".}} 
{{ template "job_delete_proc.sql".}} 
{{ template "job_undo_delete_proc.sql".}} 
{{ template "schedule_create_proc.sql".}} 
{{ template "schedule_update_proc.sql".}} 
{{ template "schedule_delete_proc.sql".}} 
{{ template "schedule_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 
{{ template "user_create_proc.sql".}} 
{{ template "user_update_proc.sql".}} 
{{ template "user_delete_proc.sql".}} 
{{ template "user_undo_delete_proc.sql".}} 
{{ template "role_create_proc.sql".}} 
{{ template "role_update_proc.sql".}} 
{{ template "role_delete_proc.sql".}} 
{{ template "role_undo_delete_proc.sql".}} 
{{ template "permission_create_proc.sql".}} 
{{ template "permission_update_proc.sql".}} 
{{ template "permission_delete_proc.sql".}} 
{{ template "permission_undo_delete_proc.sql".}} 
{{ template "accessholder_create_proc.sql".}} 
{{ template "accessholder_update_proc.sql".}} 
{{ template "accessholder_delete_proc.sql".}} 
{{ template "accessholder_undo_delete_proc.sql".}} 
{{ template "environmenttype_create_proc.sql".}} 
{{ template "environmenttype_update_proc.sql".}} 
{{ template "environmenttype_delete_proc.sql".}} 
{{ template "environmenttype_undo_delete_proc.sql".}} 
{{ template "database_create_proc.sql".}} 
{{ template "database_update_proc.sql".}} 
{{ template "database_delete_proc.sql".}} 
{{ template "database_undo_delete_proc.sql".}} 

