// -------------------------------------------------------------------
// Generated by 365admin-publish
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: List Groups
---
*/
package magicapp

import (
	"context"
	"encoding/json"
	"log"
	"time"

	_ "github.com/lib/pq"
	nats "github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/micro"
	"github.com/spf13/viper"

	"github.com/magicbutton/magic-mix/drivers"
	"github.com/magicbutton/magic-mix/flow"
	"github.com/magicbutton/magic-mix/subscription"
)

var flowEngine *flow.FlowEngine
var flowEngineeService *flow.FlowEngineService
var eventStore subscription.SubscriptionStore
var eventMessagingService *subscription.SubscriptionService

func HandleFlowRequests(req micro.Request) {
	response, err := flowEngineeService.HandleRequest(req.Data())
	if err != nil {
		req.Respond([]byte(err.Error()))
	} else {
		req.Respond([]byte(response))
	}

}

func HandleEventRequests(req micro.Request) {
	var req1 map[string]interface{}

	// Unmarshal the generic request
	err := json.Unmarshal(req.Data(), &req1)
	if err != nil {
		req.Respond([]byte(err.Error()))
	}
	response, err := eventMessagingService.HandleRequest(req1)
	if err != nil {
		req.Respond([]byte(err.Error()))
	} else {
		var b []byte
		b, err = json.Marshal(response)
		if err != nil {
			req.Respond([]byte(err.Error()))
		}
		req.Respond(b)
	}

}

func StartFlowService() {
	// Parent context cancels connecting/reconnecting altogether.
	log.Println("Starting Flow Service")
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var err error
	var nc *nats.Conn
	opts := []nats.Option{

		nats.ReconnectWait(2 * time.Second),
		nats.ReconnectHandler(func(c *nats.Conn) {
			log.Println("Reconnected to", c.ConnectedUrl())
		}),
		nats.DisconnectHandler(func(c *nats.Conn) {
			log.Println("Disconnected from NATS")
		}),
		nats.ClosedHandler(func(c *nats.Conn) {
			log.Println("NATS connection is closed.")
		}),
	}

	go func() {
		natsServer := viper.GetString("NATS")
		if natsServer == "" {
			natsServer = "nats://127.0.0.1:4222"
		}
		log.Println("Connecting to", natsServer)
		nc, err = nats.Connect(natsServer, opts...)
	}()
	retryCount := 0
WaitForEstablishedConnection:
	for {
		if err != nil {
			log.Fatal(err)
		}
		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()
		// Wait for context to be canceled either by timeout
		// or because of establishing a connection...
		select {
		case <-ctx.Done():
			break WaitForEstablishedConnection
		default:
		}

		if nc == nil || !nc.IsConnected() {
			if retryCount != 0 {
				log.Println("Connection not ready")
			}
			retryCount++
			time.Sleep(200 * time.Millisecond)
			continue
		}
		break WaitForEstablishedConnection
	}
	if ctx.Err() != nil {
		log.Fatal(ctx.Err())
	}
	log.Println("Connected")

	OpenDatabase()
	// Create a DBStorage driver that implements flow.Storage
	var storage flow.Storage = drivers.NewDBStorage()

	var emitter flow.Emitter = drivers.NewNATSEmitter(nc)
	flowEngine := flow.NewFlowEngine(storage, emitter)
	flowEngineeService = flow.NewFlowEngineService(flowEngine)
	eventStore, err = drivers.NewJetStreamSubscriptionStore(nc, "workflow_events", "workflow.events.*")
	if err != nil {
		panic(err)
	}

	//eventMessagingService = subscription.NewSubscriptionService(nc, 60)

	// utils.Setup("./.env")

	// dsn := viper.GetString("POSTGRES_DB")
	// sqldb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(dsn)))
	// db := bun.NewDB(sqldb, pgdialect.New())
	// utils.Db = db
	const name = "magic-flow"
	srv, err := micro.AddService(nc, micro.Config{
		Name: name,

		Version:     "0.0.1",
		Description: "Magic Flow",
	})
	root := srv.AddGroup(name)

	root.AddEndpoint("flow", micro.HandlerFunc(HandleFlowRequests))
	root.AddEndpoint("event", micro.HandlerFunc(HandleFlowRequests))

	for {
		if nc.IsClosed() {
			break
		}

		time.Sleep(1 * time.Second)
	}

	// Disconnect and flush pending messages
	if err := nc.Drain(); err != nil {
		log.Println(err)
	}
	log.Println("Disconnected")

}
