// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Download audit logs
---
*/
package cmds

import (
	"context"

	"github.com/magicbutton/magic-mix/execution"
	"github.com/magicbutton/magic-mix/utils"
)

func ProcessBatchPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-mix", "40-process", "12-officegraph.ps1", "", "-batchname", args[0], "-batchdefition", args[1])
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
