// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Download audit logs
---
*/
package cmds

import (
	"context"

	"github.com/magicbutton/magic-mix/execution"
	"github.com/magicbutton/magic-mix/utils"
)

func ProcessAuditPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-mix", "40-process", "10-auditlogs.ps1", "", "-year", args[0], "-month", args[1], "-day", args[2])
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
