// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Get Hub Site Spokes Pages
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-mix/execution"
)

func ExtractHubsiteSpokesPagesPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-mix", "30-sharepoint", "get-hubsite-spokes-pages.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Get Hub Site Spokes Pages")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Extract")
	return u
}
