// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Download audit logs
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-mix/execution"
)

func ProcessAuditPost() usecase.Interactor {
	type Request struct {
		Year  string `query:"year" binding:"required"`
		Month string `query:"month" binding:"required"`
		Day   string `query:"day" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-mix", "40-process", "10-auditlogs.ps1", "", "-year", input.Year, "-month", input.Month, "-day", input.Day)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Download audit logs")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Process")
	return u
}
