// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Download audit logs
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-mix/execution"
)

func ProcessBatchPost() usecase.Interactor {
	type Request struct {
		Batchname     string `query:"batchname" binding:"required"`
		Batchdefition string `query:"batchdefition" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-mix", "40-process", "12-officegraph.ps1", "", "-batchname", input.Batchname, "-batchdefition", input.Batchdefition)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Download audit logs")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Process")
	return u
}
