/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8qULN07l5U3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { BreadcrumbItem, BreadcrumbSeparator, BreadcrumbList, Breadcrumb } from "@/components/ui/breadcrumb"

export function PageTopNavigation() {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <Link href="#">
            <Button className="flex items-center gap-2" size="sm" variant="ghost">
              <HomeIcon className="h-4 w-4" />
              <span className="sr-only">Home</span>
            </Button>
          </Link>
        </BreadcrumbItem>
        <BreadcrumbSeparator>
          <ChevronRightIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
        </BreadcrumbSeparator>
        <BreadcrumbItem>
          <Link href="#">
            <Button className="flex items-center gap-2" size="sm" variant="ghost">
              Products
            </Button>
          </Link>
        </BreadcrumbItem>
        <BreadcrumbSeparator>
          <ChevronRightIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
        </BreadcrumbSeparator>
        <BreadcrumbItem>
          <Button className="flex items-center gap-2" size="sm" variant="ghost">
            Clothing
          </Button>
        </BreadcrumbItem>
        <BreadcrumbSeparator className="hidden sm:block">
          <ChevronRightIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
        </BreadcrumbSeparator>
        <BreadcrumbItem className="hidden sm:block">
          <Button className="flex items-center gap-2" size="sm" variant="ghost">
            T-Shirts
          </Button>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
