CREATE OR REPLACE VIEW devicekpi.nexi AS
SELECT (r ->> ' (column 1)')::text AS column_1,
    (r ->> ' (column 2)')::text AS column_2,
    (r ->> ' (column 3)')::text AS column_3,
    (r ->> ' (column 4)')::text AS column_4,
    (r ->> ' (column 5)')::text AS column_5,
    (r ->> ' (column 6)')::text AS column_6,
    (r ->> ' (column 7)')::text AS column_7,
    (r ->> ' (column 8)')::text AS column_8,
    (r ->> ' (column 9)')::text AS column_9,
    (r ->> ' (column 10)')::text AS column_10,
    (r ->> ' (column 11)')::text AS column_11,
    (r ->> ' (column 12)')::text AS column_12,
    (r ->> ' (column 13)')::text AS column_13,
    (r ->> ' (column 14)')::text AS column_14,
    (r ->> ' (column 15)')::text AS column_15,
    (r ->> ' (column 16)')::text AS column_16,
    (r ->> ' (column 17)')::text AS column_17,
    (r ->> ' (column 18)')::text AS column_18,
    (r ->> ' (column 19)')::text AS column_19,
    (r ->> ' (column 20)')::text AS column_20,
    (r ->> ' (column 21)')::text AS column_21,
    (r ->> ' (column 22)')::text AS column_22,
    (r ->> ' (column 23)')::text AS column_23,
    (r ->> ' (column 24)')::text AS column_24,
    (r ->> ' (column 25)')::text AS column_25,
    (r ->> ' (column 26)')::text AS column_26,
    (r ->> ' (column 27)')::text AS column_27
FROM importdata, jsonb_array_elements(data::jsonb) AS r;